server:
  port: 8281

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true

spring:
  application:
    name: org-service
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      data-locations: classpath:db/data.sql
  datasource:
    url: jdbc:h2:mem:education
    username: sa
    password: password